# Processing

Create functions to produce X matrix and A matrix needed for the model

In [1]:
import json
import numpy as np
from copy import deepcopy
import math
import os
import sys
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from pathlib import Path

In [2]:
# The higher level processing function would loop through the different file paths.
# For this notebook, we will use one of the defined file paths
data_file_path = 'truncated_data/trunc/Wed_Mar_10_2021/15_40_09.txt'

## Adjacency Matrix
Note: The adjacency matrix only needs to be pre-generated once on one of the datasets and saved as a .npy file, and subsequently loaded if needed.

In [3]:
with open(data_file_path, 'r') as traffic_data_file: # Dataset is a list of objects
    traffic_records = json.load(traffic_data_file)

In [4]:
def get_adjacency(file_path):
    '''
    Generates an Adjacency matrix
    -----------------------------
    :param str file_path: the file path of the dataset
    -----------------------------
    :returns:
        npy: Adjacency matrix
    '''
    with open(file_path, 'r') as traffic_data_file:
        traffic_records = json.load(traffic_data_file)
    
    # Format traffic_records so we can get the start & end location positions of the link
    traffic_records_formatted = []
    for record in traffic_records:
        record = deepcopy(record)
        lat_long_positions = record['Location'].split()
        record['start_pos'] = ' '. join(lat_long_positions[0:2])
        record['end_pos'] = ' '. join(lat_long_positions[2:4])
        traffic_records_formatted.append(record)
    traffic_records_formatted.sort(key=lambda x: int(x.get('LinkID')))
    
    # Generate Node Mappings
    nodes_params_dict = {}
    Nodes2LinkID = {} # not needed
    LinkID2Nodes = {} # not needed
    for i, record in enumerate(traffic_records_formatted):
        record = deepcopy(record)
        Nodes2LinkID[i] = record['LinkID']
        LinkID2Nodes[record['LinkID']] = i
        nodes_params_dict[i] = record
    
    
    # Generating a Directed Adjacency matrix
    '''
    Refer to illustrations
    To find a directed adjacency, we need to check each link (node)
    There is a directed adjacency from Node A to Node B if the end_pos of Node A is the start_pos of Node B

    This involves us having to loop through all nodes with: O(n^2) complexity
    (Computation and speed optimisation is not a concern here as this is pre-generated before training)
    '''
    nodes_count = len(nodes_params_dict)
    A = np.zeros((nodes_count,nodes_count), dtype=int)  
    # Finding the directed edges of the nodes
    for i, i_record in nodes_params_dict.items():
        # print(f'=====> Finding edges for Node: {i}, LinkID: {i_record["LinkID"]}')
        for j, j_record in nodes_params_dict.items():
            if i_record['end_pos'] == j_record['start_pos']:
                # print(f'Found a Directed Edge from Node {i} to Node {j}')
                A[i,j] = 1

    return A

In [5]:
A = get_adjacency(data_file_path)

In [6]:
print(A)
print(A.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
(53, 53)


## Feature Matrix
Note: Feature Matrix, X, would contain the output speedband as well.
> Actually get_adjacency() & get_features() can be combined together.
> Its okay to leave it separate for now.

In [11]:
def link_length(start_pos, end_pos):
    """
    Calculation of distance between two lat-long geo positions, using Haversine distance
    ------------------------------------
    :param string start_pos: lat & long separated with a space
    :param string end_pos: lat & long separated with a space
    ------------------------------------
    :returns:
        float: total length of the link
    """
    lat1, lon1 = [float(pos) for pos in start_pos.split()]
    lat2, lon2 = [float(pos) for pos in end_pos.split()]
    radius = 6371
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) * math.sin(dlat / 2) +
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) *
         math.sin(dlon / 2) * math.sin(dlon / 2))
    d = radius * (2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a)))
    return d

def get_features(file_path):
    '''
    Generates a Feature matrix
    Note: Feature Matrix, X, includes the output speedband as well. 
    -----------------------------
    :param str file_path: the file path of the dataset
    -----------------------------
    :returns:
        npy: Feature matrix - shape (num_samples, num_features)
        dict: Metadata of parameters - 
              {nodes_num, nodes_indices, nodes2linkid, linkid2nodes, nodes_features, roadcat_num, roadcat2index, index2roadcat}
    '''
    with open(file_path, 'r') as traffic_data_file:
        traffic_records = json.load(traffic_data_file)
    
    # Format traffic_records to add length of each link
    traffic_records_formatted = []
    for record in traffic_records:
        record = deepcopy(record)
        lat_long_positions = record['Location'].split()
        record['start_pos'] = ' '. join(lat_long_positions[0:2])
        record['end_pos'] = ' '. join(lat_long_positions[2:4])
        record['length'] = link_length(record['start_pos'], record['end_pos'])
        traffic_records_formatted.append(record)
    traffic_records_formatted.sort(key=lambda x: int(x.get('LinkID')))
    
    # Generate Road Category Mappings
    roadcategory_list = []
    for record in traffic_records:
        if record['RoadCategory'] not in roadcategory_list:
            roadcategory_list.append(record['RoadCategory'])
    roadcategory_list.sort()
    Index2RoadCat = {}
    RoadCat2Index = {}
    for i, cat in enumerate(roadcategory_list):
        Index2RoadCat[i] = cat
        RoadCat2Index[cat] = i

    # Generate Node Mappings
    nodes_params_dict = {}
    Nodes2LinkID = {} # not needed
    LinkID2Nodes = {} # not needed
    for i, record in enumerate(traffic_records_formatted):
        record = deepcopy(record)
        Nodes2LinkID[i] = record['LinkID']
        LinkID2Nodes[record['LinkID']] = i
        nodes_params_dict[i] = record
    
    # Create Feature Matrix
    num_features = 3
    X = []
    # Positions of Features
    # 0. SpeedBand
    # 1. RoadCategory
    # 2. Length of Link
    for i, record in nodes_params_dict.items():
        feature_row = [float(record['SpeedBand']),RoadCat2Index[record['RoadCategory']],record['length'] ]
        X.append(feature_row)
    X = np.array(X) # Convert to np array
    
    # Define parameters
    # Includes: nodes_num, nodes_indices, nodes2linkid, linkid2nodes, nodes_features, roadcat_num, roadcat2index, index2roadcat
    params = {}
    params['nodes_num'] = len(nodes_params_dict)
    params['nodes_indices'] = [i for i in nodes_params_dict.keys()]
    params['nodes2linkid'] = Nodes2LinkID
    params['linkid2nodes'] = LinkID2Nodes
    params['nodes_features'] = ['SpeedBand', 'RoadCategory', 'length']
    params['roadcat_num'] = len(roadcategory_list)
    params['roadcat2index'] = RoadCat2Index
    params['index2roadcat'] = Index2RoadCat
    
    return X, params

In [14]:
X, params = get_features(data_file_path)

In [15]:
print(X.shape)
print(X)

(53, 3)
[[3.         1.         0.08698627]
 [3.         1.         0.04609998]
 [4.         1.         0.1214745 ]
 [4.         1.         0.11285454]
 [4.         1.         0.01773246]
 [3.         1.         0.04363278]
 [4.         1.         0.03261392]
 [3.         1.         0.1313504 ]
 [5.         1.         0.04696537]
 [3.         1.         0.05844392]
 [4.         1.         0.09699181]
 [3.         1.         0.09690966]
 [4.         1.         0.05646912]
 [4.         1.         0.0756916 ]
 [4.         1.         0.0756916 ]
 [4.         1.         0.01459941]
 [4.         1.         0.01459941]
 [3.         1.         0.11190635]
 [3.         1.         0.05695016]
 [5.         0.         0.0220174 ]
 [3.         1.         0.10814834]
 [3.         1.         0.10814834]
 [3.         1.         0.03501077]
 [4.         1.         0.01996475]
 [4.         1.         0.02847569]
 [4.         1.         0.02155576]
 [4.         0.         0.00992923]
 [4.         0.     

In [20]:
print(params.keys())
params

dict_keys(['nodes_num', 'nodes_indices', 'nodes2linkid', 'linkid2nodes', 'nodes_features', 'roadcat_num', 'roadcat2index', 'index2roadcat'])


{'nodes_num': 53,
 'nodes_indices': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52],
 'nodes2linkid': {0: '103000423',
  1: '103000768',
  2: '103000843',
  3: '103000980',
  4: '103004580',
  5: '103005716',
  6: '103007532',
  7: '103007692',
  8: '103007800',
  9: '103008040',
  10: '103008060',
  11: '103009728',
  12: '103009752',
  13: '103009774',
  14: '103009775',
  15: '103009778',
  16: '103009779',
  17: '103010660',
  18: '103011232',
  19: '103054664',
  20: '103059762',
  21: '103059763',
  22: '103060004',
  23: '103060008',
  24: '103060820',
  25: '103060824',
  26: '103066000',
  27: '103072100',
  28: '103072132',
  29: '103075472',
  30: '103075952',
  31: '103075956',
  32: '103083856',
  33: '103110766',
  34